lzc-sdk-version: "0.1"
application:
  subdomain: gathio
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://gathio-app:3000/
services:
  gathio-app:
    container_name: gathio-app
    # upstream: ghcr.io/lowercasename/gathio:1.6.7
    image: ghcr.1ms.run/lowercasename/gathio:1.6.7
    depends_on:
      - gathio-db
    binds:
      - /lzcapp/var/config:/app/config
      - /lzcapp/var/static:/app/static
      - /lzcapp/var/images:/app/public/events
    setup_script: |
      if [ ! -f /app/config/config.toml ]; then
          echo "Config file does not exist, copying..."
          cp /lzcapp/pkg/content/config.toml /app/config/config.toml
          if [ -z "$LAZYCAT_APP_DOMAIN" ]; then
              echo "Error: Environment variable LAZYCAT_APP_DOMAIN is not set."
              exit 1
          fi
          sed -i.bak "s/^\( *[dD]omain *= *\)\".*\"/\1\"$LAZYCAT_APP_DOMAIN\"/" /app/config/config.toml
      fi
      grep "domain =" /app/config/config.toml
  gathio-db:
    container_name: gathio-db
    # upstream: library/mongo:4.4.30
    image: docker.1ms.run/library/mongo:4.4.30
    binds:
      - /lzcapp/var/db:/data/db
